import { useEffect, useState } from "react";

function useReveal() {
    useEffect(() => {
        const els = document.querySelectorAll("[data-reveal]");
        const io = new IntersectionObserver(
            (entries) => entries.forEach((e) => { if (e.isIntersecting) { e.target.classList.add("revealed"); io.unobserve(e.target); } }),
            { threshold: 0.08 }
        );
        els.forEach((el) => io.observe(el));
        return () => io.disconnect();
    }, []);
}

const terms = [
    {
        id: "1", icon: "👤", title: "Acceptance of Terms",
        content: `By accessing or using CoCoLaw.ai ("the Platform"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to all of these Terms, you must not use the Platform. These Terms constitute a binding legal agreement between you and CoCoLaw.ai, Inc.

We reserve the right to modify these Terms at any time. Material changes will be communicated via email and in-app notification at least 14 days before taking effect. Continued use of the Platform after changes take effect constitutes acceptance.`,
    },
    {
        id: "2", icon: "📋", title: "Description of Service",
        content: `CoCoLaw.ai is a legal technology platform providing AI-powered tools for self-represented ("pro se") litigants, including legal research assistance, document drafting, procedural guidance, evidence organization, and courtroom preparation tools.

The Platform is a software tool only. CoCoLaw.ai is not a law firm. No attorney-client relationship is created by your use of the Platform. Information generated by the Platform does not constitute legal advice. For complex legal matters, you should consult a licensed attorney in your jurisdiction.`,
    },
    {
        id: "3", icon: "✅", title: "Eligibility & Accounts",
        content: `You must be at least 18 years of age to create an account and use the Platform. By registering, you represent that all information you provide is accurate and that you will maintain its accuracy.

You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account. You must notify us immediately at security@cocolaw.ai of any unauthorized access or breach of security. We are not liable for any loss or damage arising from your failure to protect your credentials.`,
    },
    {
        id: "4", icon: "⚖️", title: "Permitted & Prohibited Use",
        content: `Permitted Use: You may use the Platform solely for lawful purposes in connection with your own pro se legal matters or, if you are a legal professional, your clients' matters consistent with your professional obligations.

Prohibited Use: You may not (a) use the Platform to generate content intended to harass, threaten, or harm any person; (b) submit false or misleading information to courts using AI-generated content without independent verification; (c) resell, sublicense, or commercially redistribute Platform outputs without written consent; (d) attempt to reverse-engineer, scrape, or extract our AI models; or (e) use the Platform in any manner that violates applicable law or these Terms.`,
    },
    {
        id: "5", icon: "🤖", title: "AI Outputs & Disclaimer",
        content: `The Platform uses artificial intelligence to generate legal documents, research, and guidance. While we strive for accuracy and currency, AI-generated content may contain errors, omissions, or outdated information.

YOU ARE SOLELY RESPONSIBLE FOR REVIEWING, VERIFYING, AND CORRECTING ALL AI-GENERATED OUTPUTS BEFORE FILING OR RELYING ON THEM. CoCoLaw.ai makes no warranty that any document generated by the Platform will be accepted by any court or comply with all applicable rules. Legal outcomes are not guaranteed.`,
    },
    {
        id: "6", icon: "💳", title: "Subscriptions & Billing",
        content: `Subscriptions are billed monthly in advance. Your subscription automatically renews at the end of each billing period unless cancelled before the renewal date. You may cancel at any time via your account settings; cancellation takes effect at the end of the current billing period with no prorated refunds.

We reserve the right to modify pricing with 30 days' notice. Continued use after a price change constitutes acceptance of the new pricing. Qualifying users may apply for in forma pauperis (IFP) reduced-rate access by contacting our support team.`,
    },
    {
        id: "7", icon: "🔐", title: "Intellectual Property",
        content: `Platform Technology: All software, AI models, interfaces, and proprietary processes constituting the Platform are owned by CoCoLaw.ai, Inc. and protected by copyright, trade secret, and other intellectual property laws. You receive a limited, non-exclusive, non-transferable license to use the Platform during your subscription term.

Your Content: You retain full ownership of all case facts, documents, and information you submit to the Platform. You grant CoCoLaw.ai a limited license to process your content solely for the purpose of delivering services to you. We do not use your content to train our AI models.`,
    },
    {
        id: "8", icon: "🛡️", title: "Limitation of Liability",
        content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, COCOLAW.AI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF CASE OUTCOME, LOST PROFITS, OR DATA LOSS, ARISING FROM YOUR USE OF OR INABILITY TO USE THE PLATFORM.

IN NO EVENT SHALL COCOLAW.AI'S TOTAL LIABILITY TO YOU EXCEED THE GREATER OF (A) THE TOTAL FEES PAID BY YOU IN THE 12 MONTHS PRECEDING THE CLAIM OR (B) $100.`,
    },
    {
        id: "9", icon: "⚖️", title: "Dispute Resolution",
        content: `Governing Law: These Terms are governed by the laws of the State of Delaware, without regard to conflict of law principles.

Arbitration: Any dispute arising under these Terms shall be resolved by binding individual arbitration under the AAA Commercial Arbitration Rules. Class actions and class arbitrations are waived. You and CoCoLaw.ai each retain the right to bring claims in small claims court for matters within that court's jurisdiction.

Informal Resolution: Before initiating arbitration, you agree to contact us at legal@cocolaw.ai and provide 30 days to attempt informal resolution.`,
    },
    {
        id: "10", icon: "📬", title: "Contact",
        content: `For general questions about these Terms, contact us at legal@cocolaw.ai. For privacy matters, contact privacy@cocolaw.ai. For billing matters, contact billing@cocolaw.ai.

CoCoLaw.ai, Inc. | legal@cocolaw.ai | Last updated: January 1, 2025`,
    },
];

const Terms = () => {
    useReveal();
    const [active, setActive] = useState(null);

    return (
        <div className="bg-gray-50 min-h-screen overflow-x-hidden">

            {/* HERO */}
            <div className="bg-[#0A0F1C] text-white py-16 px-6 text-center relative overflow-hidden" style={{ borderBottom: "3px solid #1e2740" }}>
                <div className="absolute inset-0 opacity-5 pointer-events-none">
                    <svg className="w-full h-full" viewBox="0 0 800 400" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice">
                        <defs><pattern id="tg" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0L0 0 0 40" fill="none" stroke="white" strokeWidth="0.5"/></pattern></defs>
                        <rect width="800" height="400" fill="url(#tg)"/>
                        <circle cx="100" cy="350" r="180" fill="none" stroke="white" strokeWidth="0.4"/>
                    </svg>
                </div>
                <div className="relative z-10 max-w-2xl mx-auto">
                    <p className="text-xs uppercase tracking-widest text-slate-400 mb-3 animate-fadein">Legal</p>
                    <h1 className="text-3xl md:text-4xl font-black mb-4 animate-slidein">Terms of Service</h1>
                    <p className="text-gray-400 text-sm animate-fadein-delay">Last updated: January 1, 2025 · Effective: January 1, 2025</p>
                    <p className="text-gray-400 text-sm max-w-lg mx-auto leading-relaxed mt-3 animate-fadein-delay">
                        Please read these Terms carefully before using CoCoLaw.ai. They govern your use of our platform and services.
                    </p>
                </div>
            </div>

            {/* KEY POINTS */}
            <section className="px-6 md:px-16 py-10 bg-white" style={{ borderBottom: "1px solid #e5e7eb" }}>
                <div className="max-w-4xl mx-auto">
                    <p className="text-xs uppercase tracking-widest text-slate-400 text-center mb-6" data-reveal>Key Points</p>
                    <div className="grid sm:grid-cols-3 gap-4" data-reveal>
                        {[
                            { icon: "⚖️", label: "Not a law firm", sub: "No attorney-client relationship is created" },
                            { icon: "🔍", label: "Verify AI outputs", sub: "You are responsible for reviewing all generated content" },
                            { icon: "🗓️", label: "Monthly billing", sub: "Cancel anytime, effective end of billing period" },
                        ].map((b, i) => (
                            <div key={i} className="bg-gray-50 border border-gray-200 rounded-xl px-5 py-4">
                                <div className="text-2xl mb-2">{b.icon}</div>
                                <div className="font-bold text-sm text-[#0A0F1C] mb-1">{b.label}</div>
                                <div className="text-xs text-gray-500">{b.sub}</div>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

           

            {/* TERMS SECTIONS */}
            <section className="px-6 md:px-16 py-14">
                <div className="max-w-3xl mx-auto space-y-4">
                    {terms.map((term) => (
                        <div key={term.id} id={`term-${term.id}`} data-reveal className="bg-white rounded-xl border border-gray-200 overflow-hidden">
                            <button
                                className="w-full flex items-center gap-3 px-6 py-4 text-left hover:bg-gray-50 transition"
                                onClick={() => setActive(active === term.id ? null : term.id)}
                            >
                                <span className="text-lg shrink-0">{term.icon}</span>
                                <h2 className="font-bold text-sm text-[#0A0F1C] flex-1">{term.title}</h2>
                                <span className={`text-[#0A0F1C] font-bold transition-transform duration-200 ${active === term.id ? "rotate-45" : ""}`}>+</span>
                            </button>
                            {active === term.id && (
                                <div className="px-6 pb-5 border-t border-gray-100">
                                    <p className="text-sm text-gray-600 leading-relaxed pt-4 whitespace-pre-line">{term.content}</p>
                                </div>
                            )}
                        </div>
                    ))}
                </div>
            </section>

           

            <style>{`
                @keyframes fadein  { from { opacity:0; transform:translateY(16px); } to { opacity:1; transform:translateY(0); } }
                @keyframes slidein { from { opacity:0; transform:translateY(24px); } to { opacity:1; transform:translateY(0); } }
                .animate-fadein       { animation: fadein  0.7s ease both; }
                .animate-fadein-delay { animation: fadein  0.9s 0.2s ease both; }
                .animate-slidein      { animation: slidein 0.8s 0.1s ease both; }
                [data-reveal] { opacity:0; transform:translateY(20px); transition: opacity 0.6s ease, transform 0.6s ease; }
                [data-reveal].revealed { opacity:1; transform:translateY(0); }
            `}</style>
        </div>
    );
};

export default Terms;